# Welcome to Jekyll!

title: Matt-Miller.org
email: hello@matt-miller.org
description: >- # this means to ignore newlines until "baseurl:"
  I'm Matt Miller, a rhetorician, teacher, and writer from the Midwest.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matt-miller.org" # the base hostname & protocol for your site, e.g. http://example.com
rss: rss
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
